### ISSUE TITLE
Can't save on losing focus when file is untitled. 

### ISSUE THREAD

**Issue by javadr** [kassoulet/gedit-focus-autosave#11]
Whenever I open a new file, it doesn't save it automatically on losing focus and make the following error: (in fedora 31, python 3.7, gedit 3.34.1)

`AttributeError: 'Document' object has no attribute 'set_location'`

**Comment by kassoulet** [comment]
Thank you for raising the problem. You can find the fix in the last commit.

**Comment by javadr** [comment]
Thank you for the your really useful plugin.
